# Generated by Django 4.2.3 on 2023-07-26 13:12

import buildinfo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('project', models.CharField(max_length=255, null=True)),
                ('jobset', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255, null=True)),
                ('build_id', models.IntegerField()),
                ('system', models.CharField(max_length=255, null=True)),
                ('nix_name', models.CharField(max_length=255, null=True)),
                ('queued_at', models.DateTimeField(null=True)),
                ('build_started', models.DateTimeField(null=True)),
                ('build_finished', models.DateTimeField(null=True)),
                ('post_processing_done', models.DateTimeField(null=True)),
                ('derivation_store_path', models.CharField(max_length=255, null=True)),
                ('closure_size', models.FloatField(null=True)),
                ('output_size', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutputStorePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('buildinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_store_paths', to='buildinfo.buildinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Downloadable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('BI', 'Binary'), ('SP', 'SLSA Provenance'), ('TR', 'Test Report'), ('TL', 'Test Log'), ('SB', 'SBOM'), ('VS', 'Vulnerability Scan'), ('OT', 'Other')], default='OT', max_length=2)),
                ('file_name', models.FileField(upload_to=buildinfo.models.files_directory)),
                ('build_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloadables', to='buildinfo.buildinfo')),
            ],
        ),
        migrations.AddField(
            model_name='buildinfo',
            name='build_server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='build_infos', to='buildinfo.buildserver'),
        ),
    ]
