# Generated by Django 4.2.3 on 2023-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildinfo',
            options={'ordering': ['build_server__name', 'build_id']},
        ),
        migrations.AlterModelOptions(
            name='buildserver',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='outputstorepath',
            options={'ordering': ['path']},
        ),
        migrations.AlterField(
            model_name='buildserver',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
