# Generated by Django 4.2.3 on 2023-07-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo', '0002_alter_buildinfo_options_alter_buildserver_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadable',
            old_name='build_info',
            new_name='buildinfo',
        ),
    ]
