# Generated by Django 4.2.3 on 2023-07-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildinfo', '0003_rename_build_info_downloadable_buildinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
